version: "3.8"

services:
  app1:
    build:
      context: .
    ports:
      - "6081:6080"
    environment:
      - NODE_ENV=production
  app2:
    build:
      context: .
    ports:
      - "6082:6080"
    environment:
      - NODE_ENV=production
  app3:
    build:
      context: .
    ports:
      - "6083:6080"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "6080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
